### ISSUE TITLE
Unable to parse properly

### ISSUE THREAD

**Issue by songjinlian** [PKISolutions/Asn1DerParser.NET#15]
[Contents.zip](https://github.com/PKISolutions/Asn1Editor.WPF/files/15212904/Contents.zip)
The attachment cannot be parsed properly. It can be parsed using similar software. It can be confirmed that it is not a data format issue.

**Comment by Crypt32** [comment]
I can confirm bug. The problem is that ASN.1 parser tries to recurse in UTF8String type which must be primitive and nested types must be ignored.

**Comment by Crypt32** [comment]
This issue is fixed in underlying parser (the issue is not related to ASN.1 editor). Fix will be available in next release of ASN.1 Editor.

**Comment by Crypt32** [comment]
FYI: based on your sample content file, I found some issues with GeneralizedTime parsing when timezone is explicitly specified:
![image](https://github.com/user-attachments/assets/70f323a5-0452-4122-afbe-4426b532e061)

I will work on this issue in separate ticket.
