### ISSUE TITLE
Maybe it is a bug in DateTimeUtils.cs

### ISSUE THREAD

**Issue by scegg** [PKISolutions/Asn1DerParser.NET#4]
https://github.com/PKISolutions/Asn1DerParser.NET/blob/master/Asn1Parser/Utils/DateTimeUtils.cs

line 21-22:
I think your + - is set oppositely.

**Comment by scegg** [comment]
https://en.wikipedia.org/wiki/ISO_8601

**Comment by Crypt32** [comment]
Indeed, it was a bug.
