### ISSUE TITLE
encoding is not right in UniversalString

### ISSUE THREAD

**Issue by scegg** [PKISolutions/Asn1DerParser.NET#5]
https://github.com/PKISolutions/Asn1DerParser.NET/blob/master/Asn1Parser/Universal/Asn1UniversalString.cs

Line 50 and 53:

The encoding of "abc" in UTF32 is (in dec): 97 00 00 00 98 00 00 00 99 00 00 00
The Reverse() will make it to: 00 00 00 99 00 00 00 98 00 00 00 97

That may not be your wanted result right?

**Comment by Crypt32** [comment]
Agree. The intent was to reverse 4-byte block for every character. .NET returns strings in little-endian byte sequence and we need big-endian sequence for ASN.1

**Comment by scegg** [comment]
var data = Encoding.UTF32.GetBytes(value.Reverse().ToArray()).Reverse().ToArray();

**Comment by Crypt32** [comment]
thanks for reporting, I've fixed this bug.
